org: greedyman
app: tesseroid
service: tesseroid-functions
frameworkVersion: ">=1.34.0 <2.0.0"

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.7 #fixed with pipenv
  region: us-east-1
  memorySize: 128
  profile: aws_educate_serverless

custom:
  pythonRequirements:
    usePipenv: true
    useDownloadCache: true
    useStaticCache: true
    
functions:
  main:
    handler: handler.main
    layers:
      - arn:aws:lambda:us-east-1:260659138565:layer:layer_fast:1
      # Update this ARN after you've deployed the tesseract layer
      # - arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:layer:tesseract:1
    events:
      - http:
          path: ocr
          method: post
      
# resources- Raw cloudformation code