org: greedyman
app: ocr
service: tesseroid_functions
frameworkVersion: ">=1.34.0 <2.0.0"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: python3.6 #issue- dont change version
  region: ap-south-1


functions:
  main:
    handler: handler.main
    layers:
      - arn:aws:lambda:eu-central-1:105926622732:layer:tesseract:10
      # Update this ARN after you've deployed the tesseract layer
      # - arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:layer:tesseract:1
    events:
      - http:
          path: ocr
          method: post